export const categories = [
  { id: "video", label: "视频" },
  { id: "image", label: "图片" },
  { id: "document", label: "文档" },
  { id: "developer", label: "开发者" },
];

export const tools = [
  {
    id: "video-to-gif",
    title: "视频转 GIF",
    description: "裁剪片段，生成可循环播放的 GIF。",
    category: "video",
    icon: "film",
    accent: "lime",
    engine: "local",
    accept: "video/*",
    formats: "MP4 / MOV / WEBM / AVI",
  },
  {
    id: "video-frame-extractor",
    title: "视频抽帧",
    description: "按间隔提取清晰静帧，打包成 ZIP。",
    category: "video",
    icon: "scan",
    accent: "orange",
    engine: "local",
    accept: "video/*",
    formats: "MP4 / MOV / WEBM / AVI",
  },
  {
    id: "video-compressor",
    title: "视频压缩",
    description: "缩小体积，尽量保留观感，适合发送和上传。",
    category: "video",
    icon: "minimize",
    accent: "lime",
    engine: "ffmpeg",
    accept: "video/*",
    formats: "MP4 / MOV / WEBM / MKV",
  },
  {
    id: "video-to-audio",
    title: "视频转音频",
    description: "从视频中提取音轨，导出 MP3 / WAV / AAC。",
    category: "video",
    icon: "music",
    accent: "orange",
    engine: "ffmpeg",
    accept: "video/*",
    formats: "MP4 / MOV / WEBM / MKV",
  },
  {
    id: "image-compressor",
    title: "图片压缩",
    description: "批量压缩 JPG / PNG / WEBP，肉眼几乎无损。",
    category: "image",
    icon: "image",
    accent: "teal",
    engine: "local",
    accept: "image/*",
    formats: "JPG / PNG / WEBP / BMP",
  },
  {
    id: "image-convert",
    title: "图片格式转换",
    description: "在 JPG、PNG、WEBP 之间互转，可调质量。",
    category: "image",
    icon: "refresh",
    accent: "teal",
    engine: "local",
    accept: "image/*",
    formats: "JPG / PNG / WEBP / BMP / GIF",
  },
  {
    id: "image-resize",
    title: "图片缩放",
    description: "按宽度、高度或百分比批量调整尺寸。",
    category: "image",
    icon: "maximize",
    accent: "lime",
    engine: "local",
    accept: "image/*",
    formats: "JPG / PNG / WEBP",
  },
  {
    id: "image-watermark",
    title: "图片水印",
    description: "批量添加文字水印，可调位置、透明度和字号。",
    category: "image",
    icon: "type",
    accent: "orange",
    engine: "local",
    accept: "image/*",
    formats: "JPG / PNG / WEBP",
  },
  {
    id: "pdf-merge",
    title: "PDF 合并",
    description: "把多个 PDF 按顺序合成一个文件。",
    category: "document",
    icon: "file",
    accent: "lime",
    engine: "local",
    accept: "application/pdf",
    formats: "PDF",
  },
  {
    id: "pdf-split",
    title: "PDF 拆分",
    description: "按页码范围拆出新的 PDF。",
    category: "document",
    icon: "split",
    accent: "orange",
    engine: "local",
    accept: "application/pdf",
    formats: "PDF",
  },
  {
    id: "images-to-pdf",
    title: "图片转 PDF",
    description: "把多张图片排成一册 PDF，适合扫描件和截图。",
    category: "document",
    icon: "book",
    accent: "teal",
    engine: "local",
    accept: "image/*",
    formats: "JPG / PNG / WEBP",
  },
  {
    id: "json-formatter",
    title: "JSON 格式化",
    description: "美化、压缩、校验 JSON，一键复制结果。",
    category: "developer",
    icon: "code",
    accent: "lime",
    engine: "local",
    accept: "",
    formats: "JSON",
  },
  {
    id: "qr-generator",
    title: "二维码生成",
    description: "把链接、文本或名片生成可下载的二维码。",
    category: "developer",
    icon: "qr",
    accent: "orange",
    engine: "local",
    accept: "",
    formats: "PNG",
  },
  {
    id: "base64-codec",
    title: "Base64 编解码",
    description: "文本与 Base64 互转，也支持文件转 Data URL。",
    category: "developer",
    icon: "binary",
    accent: "teal",
    engine: "local",
    accept: "",
    formats: "文本 / 文件",
  },
  {
    id: "hash-generator",
    title: "哈希计算",
    description: "计算 SHA-1 / SHA-256 / SHA-512，用于校验文件。",
    category: "developer",
    icon: "hash",
    accent: "lime",
    engine: "local",
    accept: "",
    formats: "文本 / 文件",
  },
  {
    id: "regex-tester",
    title: "正则测试",
    description: "实时查看匹配结果，支持常用标志。",
    category: "developer",
    icon: "regex",
    accent: "orange",
    engine: "local",
    accept: "",
    formats: "文本",
  },
  {
    id: "url-codec",
    title: "URL 编解码",
    description: "编码或还原查询参数和特殊字符。",
    category: "developer",
    icon: "link",
    accent: "teal",
    engine: "local",
    accept: "",
    formats: "文本",
  },
  {
    id: "uuid-generator",
    title: "UUID 生成",
    description: "批量生成 UUID v4，可复制或下载。",
    category: "developer",
    icon: "key",
    accent: "lime",
    engine: "local",
    accept: "",
    formats: "文本",
  },
];

export function getTool(id) {
  return tools.find((tool) => tool.id === id);
}

export function toolsByCategory(categoryId) {
  return tools.filter((tool) => tool.category === categoryId);
}
